# atomic files
data_path: C:/Users/ronni/OneDrive/Desktop/Optimal-MRS-Project/atomic_data_path
dataset: BERT_RES50_Amazon_Fashion

# dataset config
USER_ID_FIELD: user_id
ITEM_ID_FIELD: parent_asin

INTERACTION_FEATURE_FIELDS: [text_BERT_emb]
USER_FEATURE_FIELDS: []
ITEM_FEATURE_FIELDS: [desc_BERT_emb, img_RES50_emb]

# explicitly declare negative item ID field
NEG_ITEM_ID_FIELD: neg_parent_asin

# get the embedding sizes for the text and image modalities to be utilized by custom models
text_BERT_emb: 768
desc_BERT_emb: 768 
img_RES50_emb: 2048

load_col:
  inter:  [user_id, parent_asin, rating, timestamp, text_BERT_emb]
  user:   [user_id]
  item:   [parent_asin, average_rating, rating_number, price, desc_BERT_emb, img_RES50_emb]

# normalize time stamp due to its large value that is overriding the important signals from other features during fusion
normalize_field: [timestamp]

field_separator: "\t"
seq_separator: " "

# set rating threshold >= 4 as positive interaction (label = 1) and anything else as negative interaction (label = 0)
threshold:
  rating: 4

# use the default negative-sampling from recbole at a rate of 1 negative per positive
train_neg_sample_args: {}

# set name of label column as 'label' for recbole
LABEL_FIELD: label

#model: FM
embedding_size: 64
loss_type: BPRLoss
train_batch_size: 1024
eval_batch_size: 1024
epochs: 35

metrics: [Recall, MRR, NDCG, GAUC]

learner: adam
learning_rate: 0.001

# pick this metric with @K for best model selection
valid_metric: NDCG@10

eval_args:
  split: {'RS': [0.8, 0.1, 0.1]}
  group_by: user
  order: RO
  # do negative sampling evaluation at a rate of 1 positive and 100 negatives per user to speed up training over full_sort
  mode: uni100
  full_sort: False

# add reproducibility for model experiments ran
seed: 42
reproducibility: True