# atomic file and dataset folder references
data_path: C:/Users/ronni/OneDrive/Desktop/Optimal-MRS-Project/atomic_data_path
dataset: DistilBERT_RES50_Amazon_Fashion

# specify user and item ID fields
USER_ID_FIELD: user_id
ITEM_ID_FIELD: parent_asin

# specify important modality encoder embedding fields from each atomic file
INTERACTION_FEATURE_FIELDS: [text_DistilBERT_emb]
USER_FEATURE_FIELDS: []
ITEM_FEATURE_FIELDS: [desc_DistilBERT_emb, img_RES50_emb]

# TURN OFF FOR ADAPTED FUSION MODELS
##########################################
#numerical_features:
#  - text_DistilBERT_emb
#  - desc_DistilBERT_emb
#  - img_RES50_emb

#FEAT_COL_FIELDS:
#  text_DistilBERT_emb: 768
#  desc_DistilBERT_emb: 768
#  img_RES50_emb: 2048

#USE_FEAT_COLS: [user_id, parent_asin, text_DistilBERT_emb, desc_DistilBERT_emb, img_RES50_emb]
##########################################

# add in references for adapted fusion models
text_field: "text_DistilBERT_emb"
desc_field: "desc_DistilBERT_emb"
img_field: "img_RES50_emb"

save_dataset: False

# explicitly declare expected negative item ID field
NEG_ITEM_ID_FIELD: neg_parent_asin

# specify the expected embedding sizes for the text and image modality encoder embeddings
text_DistilBERT_emb: 768
desc_DistilBERT_emb: 768 
img_RES50_emb: 2048

# specify all the columns to load in each atomic file
load_col:
  inter:  [user_id, parent_asin, rating, timestamp, text_DistilBERT_emb]
  user:   [user_id]
  item:   [parent_asin, average_rating, rating_number, price, desc_DistilBERT_emb, img_RES50_emb]

# normalize timestamp due to its large value and prevent it from overriding important signals in final scoring vector
normalize_field: [timestamp]

# specify separators used in the atomic files
field_separator: "\t"
seq_separator: " "

# set rating threshold >= 4 as positive interaction (label = 1) and anything else as negative interaction (label = 0)
threshold:
  rating: 4

# sample a random negative interaction for each positive interaction during training
train_neg_sample_args:
  sample_num: 1
  distribution: 'uniform'

# declare the label column for rating as required by recbole when using thresholds
LABEL_FIELD: label

# set expected scoring vector dimension
embedding_size: 64

# set loss function to use when training model
loss_type: BPRLoss

# set batch sizes for training, validation and test processes
train_batch_size: 512
eval_batch_size: 512

# set how many times we want the model to pass over the complete training dataset during training
epochs: 35

# list the evaluation metrics we want recbole to calculate after training, valdiation and test
metrics: [Recall, MRR, NDCG, GAUC]

# set optimizer and learning rate for the model hyperparameters
learner: adam
learning_rate: 0.001

# use this metric to help recbole determine the best model found during the training process
valid_metric: NDCG@10

eval_args:
  # split the dataset we provide recbole into 80/10/10 splits for training, validation and test sets
  split: {'RS': [0.8, 0.1, 0.1]}
  group_by: user
  # use random ordering to shuffle the interaction data before the split
  order: RO
  # during the validation and test process tell recbole to use uniform random negative sampling at a rate of 10 negatives for one positive for ranking calculation
  mode: uni10
  # do not evaluate the model against all items in the dataset as this process is too long, instead use uni100 to do this
  full_sort: False

# tell recbole to make sure the experiment is reproducible by setting a fixed seed number and declaring reproducibility = True 
seed: 42
reproducibility: False